app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth
Route::get('/auth/login', 'Auth\AuthController@getLogin');
Route::post('/auth/login', 'Auth\AuthController@postLogin');
Route::get('/auth/logout', 'Auth\AuthController@getLogout');
Route::get('/register', 'Auth\AuthController@getRegister');
Route::post('/register', 'Auth\AuthController@postRegister');


// Authentication routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


/*// Roles
Route::get('/', [
  'middleware' => ['auth', 'roles'],
  'uses' => 'AppController@index',
  'roles' => ['user']
]);
Route::get('/home', [
  'middleware' => ['auth', 'roles'],
  'uses' => 'AppController@index',
  'roles' => ['user']
]);*/

// BACKEND - routes
Route::group([
  'prefix' => 'admin',
  'middleware' => ['auth', 'roles'],
  'roles' => ['administrator','Root','Manager','Company Manager']
  ], 
  function () { 
    Route::get('/', 'AppController@backend');
});

Route::group([
  'middleware' => ['auth', 'roles'],
  'roles' => ['administrator','Root', 'Company Manager']
  ], 
  function(){
    Route::resource('noticias', 'Backend\NoticiasController');
    Route::resource('formsLandings', 'Backend\FormsLandingsController', ['except' => ['store']]);
    Route::resource('landings', 'Backend\LandingsController');
});


//FRONTEND - Vistas
Route::get('/', 'IndexController@index');
Route::get('filosofia', 'FilosofiaController@index');
Route::get('internacion-domiciliaria', 'InternacionDomiciliariaController@index');
Route::get('rrhh', 'RrhhController@index');
Route::get('familia', 'FamiliaController@index');
Route::get('empresas', 'EmpresasController@index');
Route::get('serviciosempresas/areaprotegida', 'ProtegidaController@index');
Route::get('serviciosempresas/areacardio', 'AreacardioController@index');
Route::get('serviciosempresas/medicinalaboral', 'MedicinalaboralController@index');
Route::get('serviciosempresas/eventos', 'EventosController@index');
Route::get('serviciosempresas/planes', 'PlanesController@index');
Route::get('serviciosempresas/serviciomedico', 'ServiciomedicoController@index');
Route::get('serviciosempresas/cursos', 'CursosController@index');
Route::get('serviciosempresas/cursos/mail', 'CursosController@index');
Route::get('serviciosempresas/medicinalaboral/mail', 'MedicinalaboralController@index');
Route::get('/novedades', 'NoticiasController@index');
Route::get('/novedad/{slug}', 'NoticiasController@show');
Route::get('/novedades/{order}','NoticiasController@showOrder');
//landing
Route::get('form/{slug}', 'LandingsController@show');
//form landing
Route::post('formsLandings', [
  'uses' => 'Backend\FormsLandingsController@store',
  'as' => 'formsLandings.store'
]);


//FRONTEND - Posts
Route::post('postrrhh','RrhhController@store');
Route::post('postfamilia','FamiliaController@store');
Route::post('serviciosempresas/areaprotegidapost','ServiciosController@store');
Route::post('serviciosempresas/areacardiopost','ServiciosController@store');
Route::post('serviciosempresas/medicinalaboralpost','ServiciosController@store');
Route::post('serviciosempresas/eventospost','ServiciosController@store');
Route::post('serviciosempresas/planespost','ServiciosController@store');
Route::post('serviciosempresas/serviciomedicopost','ServiciosController@store');
Route::post('serviciosempresas/cursospost','ServiciosController@store');
Route::post('filosofiapost','ServiciosController@store');
Route::post('internacion-domiciliariapost','ServiciosController@store');
Route::post('serviciosempresas/cursos/mailpost','ServiciosController@store');
Route::post('serviciosempresas/medicinalaboral/mailpost', 'ServiciosController@store');


//Sitemap 
Route::get('sitemap.xml', 'SitemapController@sitemap');
//Tester
/*Route::get('email', function()
{
    return view('emails.servicios');
});*/



/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
        require config('infyom.laravel_generator.path.api_routes');
    });
});

app/Http/Controllers/Backend/FilesRenamerController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Flash;
use InfyOm\Generator\Controller\AppBaseController;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\Banners;
use Input;
use File;

class FilesRenamerController extends AppBaseController
{

    /**
     * Remove the specified Banners from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function rename( $fileToRename , $type )
    {
    		$file										= $fileToRename;
        $fileOriginalExtension 	= $file->getClientOriginalExtension(); 
        $fileNewName  					= time() . $type . $fileOriginalExtension;
        return $fileNewName;
    }
}

app/Http/Controllers/Backend/FormsLandingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests;
use App\Http\Requests\CreateFormsLandingsRequest;
use App\Http\Requests\UpdateFormsLandingsRequest;
use App\Repositories\FormsLandingsRepository;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use InfyOm\Generator\Controller\AppBaseController;
use App\Models\Landings;
use DB;
use Mail;

class FormsLandingsController extends AppBaseController
{
    /** @var  FormsLandingsRepository */
    private $formsLandingsRepository;
    //protected $clientEmail = 'giannina@wirallinteractive.com.ar';
    //protected $clientSendEmail = 'giannina@wirallinteractive.com.ar';
    protected $clientEmail = 'contacto@masvida.com.ar';
    protected $clientSendEmail = 'contacto@masvida.com.ar';

    public function __construct(FormsLandingsRepository $formsLandingsRepo)
    {
        $this->formsLandingsRepository = $formsLandingsRepo;
    }

    /**
     * Display a listing of the FormsLandings.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->formsLandingsRepository->pushCriteria(new RequestCriteria($request));
        //$formsLandings = $this->formsLandingsRepository->all();

        $formsLandings = DB::table('landings') 
            ->join('forms_landings', 'landings.id', '=', 'forms_landings.id_landing')
            ->where('forms_landings.deleted_at', '=', NULL)
            ->select('forms_landings.id','forms_landings.created_at AS fechaFormsLandings','forms_landings.nombre', 
                    'forms_landings.apellido','forms_landings.email',  'forms_landings.telefono', 'landings.titulo AS tituloLanding')
            ->get();

        return view('backend.formsLandings.index')
            ->with('formsLandings', $formsLandings);
    }

    /**
     * Show the form for creating a new FormsLandings.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.formsLandings.create');
    }

    /**
     * Store a newly created FormsLandings in storage.
     *
     * @param CreateFormsLandingsRequest $request
     *
     * @return Response
     */
    public function store(CreateFormsLandingsRequest $request)
    {
        $input = $request->all();

        $formsLandings = $this->formsLandingsRepository->create($input);

        Flash::success('Mensaje enviado con éxito.');

        $landings = Landings::where('id' , '=', $request->input('id_landing'))->first();

        $inicio = strtotime($landings->inicio); 
        $fin = strtotime($landings->fin); 
        $fecha = strtotime(date("Y-m-d")); 
         
        if ($fecha >= $inicio && $fecha <= $fin ) {
            $activo = true;
        } else {
            $activo = false;
        }

        // Data message
        $data = array(
            'email'     => $formsLandings->email,
            'subject'   => 'Contacto desde el sitio +Vida (Landing)',
            //'to'            => 'giannina@wirallinteractive.com.ar'
            'to'            => 'contacto@masvida.com.ar'
        );
        // Mail to Mas Vida
        $htmlData = array(
            'landings' => $landings,
            'nombre'   => $formsLandings->nombre,
            'apellido' => $formsLandings->apellido,
            'telefono' => $formsLandings->telefono,
            'email'  => $formsLandings->email
        );

        Mail::send('emails.new-contact-landing', $htmlData, function ($message) use ($data){
          $message->from($data['email'], 'Mas vida Website');
          $message->to( $data['to'] , 'Mas Vida' )->subject($data['subject']);
        });

        return view('partials.landing')->with('landings', $landings)->with('activo', $activo);
    }

    /**
     * Display the specified FormsLandings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $formsLandings = $this->formsLandingsRepository->findWithoutFail($id);

        if (empty($formsLandings)) {
            Flash::error('FormsLandings not found');

            return redirect(route('formsLandings.index'));
        }

        $landing = Landings::where('id' , '=', $formsLandings->id_landing)->first();
        return view('backend.formsLandings.show')->with('formsLandings', $formsLandings)->with('landing', $landing);
    }

    /**
     * Show the form for editing the specified FormsLandings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $formsLandings = $this->formsLandingsRepository->findWithoutFail($id);

        if (empty($formsLandings)) {
            Flash::error('FormsLandings not found');

            return redirect(route('formsLandings.index'));
        }

        return view('backend.formsLandings.edit')->with('formsLandings', $formsLandings);
    }

    /**
     * Update the specified FormsLandings in storage.
     *
     * @param  int              $id
     * @param UpdateFormsLandingsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFormsLandingsRequest $request)
    {
        $formsLandings = $this->formsLandingsRepository->findWithoutFail($id);

        if (empty($formsLandings)) {
            Flash::error('FormsLandings not found');

            return redirect(route('formsLandings.index'));
        }

        $formsLandings = $this->formsLandingsRepository->update($request->all(), $id);

        Flash::success('FormsLandings updated successfully.');
        return redirect(route('formsLandings.index'));
    }

    /**
     * Remove the specified FormsLandings from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $formsLandings = $this->formsLandingsRepository->findWithoutFail($id);

        if (empty($formsLandings)) {
            Flash::error('FormsLandings not found');

            return redirect(route('formsLandings.index'));
        }

        $this->formsLandingsRepository->delete($id);

        Flash::success('Mensaje eliminado con éxito');

        return redirect(route('formsLandings.index'));
    }
}

app/Http/Controllers/Backend/LandingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests;
use App\Http\Requests\CreateLandingsRequest;
use App\Http\Requests\UpdateLandingsRequest;
use App\Repositories\LandingsRepository;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use InfyOm\Generator\Controller\AppBaseController;
use App\Models\Landings;
use Input;
use File;

class LandingsController extends AppBaseController
{
    /** @var  LandingsRepository */
    private $landingsRepository;
    private $path;
    private $servicios;

    public function __construct(LandingsRepository $landingsRepo)
    {
        $this->landingsRepository = $landingsRepo;
        $this->path = public_path().'/uploads/landings/';
        $this->servicios  = array('Medicina Laboral', 'Área Protegida', 'Área Cardio', 'Cursos', 
                                'Servicio de Médico y Enfermería en Planta', 
                                'Eventos', 'Internación Domiciliaria', 'Novedades', 
                                'Recursos Humanos', 'Convenio y Planes para Empleados', 'Familia');
    }

    /**
     * Display a listing of the Landings.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->landingsRepository->pushCriteria(new RequestCriteria($request));
        $landings = $this->landingsRepository->all();

        return view('backend.landings.index')
            ->with('landings', $landings);
    }

    /**
     * Show the form for creating a new Landings.
     *
     * @return Response
     */
    public function create()
    {
        $servicios_list = $this->servicios;
        return view('backend.landings.create')->with('servicios_list', $servicios_list);
    }

    /**
     * Store a newly created Landings in storage.
     *
     * @param CreateLandingsRequest $request
     *
     * @return Response
     */
    public function store(CreateLandingsRequest $request)
    {
        // Si no existe la carpeta la crea la primera vez
        if (!file_exists(public_path().'/uploads/landings/')) {
          mkdir(public_path().'/uploads/landings/', 0777, true);
        }

        // Genero Imagen
        $newName = app('App\Http\Controllers\Backend\FilesRenamerController')->rename( $request->file('imagen') , '_land.' );

        // Guarda Imagen
        $request->file('imagen')->move( $this->path , $newName ); 
        
        $landing = Landings::create([
            'titulo' => $request->input('titulo'),
            'texto' => $request->input('texto'),
            'texto_caducidad' => $request->input('texto_caducidad'),
            'imagen' => $newName, 
            'inicio' => $request->input('inicio'),
            'fin' => $request->input('fin'),
            'url' => $request->input('url'),
            'servicios' => $request->input('servicios'),
            'servicios' => $request->input('servicios'),
        ]);

        Flash::success('Landing creada con éxito.');
        return redirect(route('landings.index'));
    }

    /**
     * Display the specified Landings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $landings = $this->landingsRepository->findWithoutFail($id);

        if (empty($landings)) {
            Flash::error('Landings not found');

            return redirect(route('landings.index'));
        }

        return view('backend.landings.show')->with('landings', $landings);
    }

    /**
     * Show the form for editing the specified Landings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $landings = $this->landingsRepository->findWithoutFail($id);

        if (empty($landings)) {
            Flash::error('Landings not found');

            return redirect(route('landings.index'));
        }

        $servicios_list = $this->servicios;
        return view('backend.landings.edit')->with('landings', $landings)->with('servicios_list', $servicios_list);

    }

    /**
     * Update the specified Landings in storage.
     *
     * @param  int              $id
     * @param UpdateLandingsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateLandingsRequest $request)
    {

        $landings = $this->landingsRepository->findWithoutFail($id);
        if (empty($landings)) {
            Flash::error('Landing not found');
            return redirect(route('landings.index'));
        }

        if ( $request->hasFile('imagen') ) {
            $newName = app('App\Http\Controllers\Backend\FilesRenamerController')->rename( $request->file('imagen') , '_land.' );
            $request->file('imagen')->move( $this->path , $newName ); 
            File::delete( $this->path.$landings->imagen );
            $update = $this->landingsRepository->update(['imagen' => $newName], $id);
        }

        $update = $this->landingsRepository->update([
            'titulo' => $request->input('titulo'),
            'texto' => $request->input('texto'),
            'texto_caducidad' => $request->input('texto_caducidad'),
            'inicio' => $request->input('inicio'),
            'fin' => $request->input('fin'),
            'url' => $request->input('url'),
            'servicios' => $request->input('servicios')
            ], $id)
        ;

        Flash::success('Landing editada con éxito.');
        return redirect(route('landings.index'));
    }

    /**
     * Remove the specified Landings from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $landings = $this->landingsRepository->findWithoutFail($id);

        if (empty($landings)) {
            Flash::error('Landings not found');

            return redirect(route('landings.index'));
        }

        $this->landingsRepository->delete($id);

        Flash::success('Landings eliminada con éxito.');

        return redirect(route('landings.index'));
    }
}

resources/views/backend/noticias/create.blade.php
@extends('backend.main')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Crear Noticia</h1>
                <hr>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::open(['route' => 'noticias.store', 'files' => true]) !!}

                @include('backend.noticias.fields')

            {!! Form::close() !!}
        </div>

    </div>
@endsection

@section('viewscripts')
    <script src="{{ asset('js/backend/noticias.js') }}"></script>
    <script src="{{ asset('js/backend/tinymce-init.js') }}"></script>
@endsection

resources/views/backend/noticias/edit.blade.php
@extends('backend.main')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Editar Noticia</h1>
                <hr>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::model($noticias, ['route' => ['noticias.update', $noticias->id], 'method' => 'patch', 'files' => true]) !!}

            @include('backend.noticias.fields_edit')

            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('viewscripts')
    <script src="{{ asset('js/backend/tinymce-init.js') }}"></script>
@endsection

resources/views/backend/noticias/fields.blade.php
<!-- Titulo Field -->
<div class="form-group col-sm-12">
    {!! Form::label('titulo', 'Titulo:') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control', 'id' => 'titulo']) !!}
</div>

<!-- Url Field -->
<div class="form-group col-sm-12">
    {!! Form::label('url', 'Url:') !!}
    {!! Form::text('url', null, ['class' => 'form-control', 'id' => 'url']) !!}
</div>

<!-- Titulo Field -->
<div class="form-group col-sm-12">
    {!! Form::label('sub_titulo', 'Sub Titulo:') !!}
    {!! Form::text('sub_titulo', null, ['class' => 'form-control']) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control  tinymce-init']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-12">
    {!! Form::label('image', 'Imagen Portada:') !!} <small>Tamaño recomendado: 1200px x 500px</small>
    {!! Form::file('image', ['class' => 'filestyle', 'data-buttonText' => 'Buscar']) !!}
</div>

<div class="col-sm-12">
    <br>
</div>

<div class="clearfix"></div>
<!-- Image Field -->
<div class="form-group col-sm-12">
    {!! Form::label('image_thumb', 'Imagen Miniatura:') !!} <small>Tamaño recomendado: 500px x 500px</small>
    {!! Form::file('image_thumb', ['class' => 'filestyle', 'data-buttonText' => 'Buscar']) !!}
</div>
<div class="clearfix"></div>

<br>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('noticias.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/backend/noticias/fields_edit.blade.php
<!-- Titulo Field -->
<div class="form-group col-sm-12">
    {!! Form::label('titulo', 'Titulo:') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<!-- Url Field -->
<div class="form-group col-sm-12">
    {!! Form::label('url', 'Url:') !!} <small> (La url no puede ser editada para evitar inconsistencias en SEO.) </small>
    {!! Form::text('url', null, ['class' => 'form-control', 'disabled' => 'true']) !!}
    <input id="token" type="hidden" name="url" value="{{ $noticias->url}}">
</div>

<!-- Titulo Field -->
<div class="form-group col-sm-12">
    {!! Form::label('sub_titulo', 'Sub Titulo:') !!}
    {!! Form::text('sub_titulo', null, ['class' => 'form-control']) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control tinymce-init']) !!}
</div>

<!-- Image Field --> 
<div class="col-sm-12">
    {!! Form::label('image', 'Imagen Portada:') !!} <small>Tamaño recomendado: 1200px x 500px</small>
    </div>
<div class="col-sm-2">
    {!! Html::image('uploads/noticias/'.$noticias->image, 'Imagen', ['class' => 'img-responsive center-block']) !!}
</div>
<div class="col-sm-10">
    {!! Form::file('image', ['class' => 'filestyle', 'data-buttonText' => 'Buscar', 'data-placeholder' => $noticias->image]) !!}

</div>

<div class="col-sm-12">
    <br>
</div>

<!-- Image Field -->   
<div class="col-sm-12">
    {!! Form::label('image_thumb', 'Imagen Miniatura:') !!} <small>Tamaño recomendado: 500px x 500px</small>
    </div>
<div class="col-sm-2">
    {!! Html::image('uploads/noticias/'.$noticias->image_thumb, 'Imagen', ['class' => 'img-responsive center-block']) !!}
</div>
<div class="col-sm-10">
    {!! Form::file('image_thumb', ['class' => 'filestyle', 'data-buttonText' => 'Buscar', 'data-placeholder' => $noticias->image_thumb]) !!}
</div>

<div class="clearfix"></div>

<br>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('noticias.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/backend/noticias/index.blade.php
@extends('backend.main')

@section('content')

	<div class="container">

	    <h1 class="pull-left"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Noticias</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('noticias.create') !!}">
            <span class="glyphicon glyphicon-plus"></span> 
            Agregar
        </a>
        <hr>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('backend.noticias.table')
    </div>   
@endsection

resources/views/backend/noticias/show.blade.php
@extends('backend.main')

@section('content')
    @include('backend.noticias.show_fields')

    <div class="form-group">
           <a href="{!! route('noticias.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/backend/noticias/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $noticias->id !!}</p>
</div>

<!-- Titulo Field -->
<div class="form-group">
    {!! Form::label('titulo', 'Titulo:') !!}
    <p>{!! $noticias->titulo !!}</p>
</div>

<!-- Titulo Field -->
<div class="form-group">
    {!! Form::label('titulo', 'Titulo:') !!}
    <p>{!! $noticias->titulo !!}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{!! $noticias->descripcion !!}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{!! $noticias->image !!}</p>
</div>

<!-- Url Field -->
<div class="form-group">
    {!! Form::label('url', 'Url:') !!}
    <p>{!! $noticias->url !!}</p>
</div>

resources/views/backend/noticias/table.blade.php
<table class="table table-responsive" id="tabla-datatable">
    <thead>
        <th>Imagen Miniatura</th>
        <th>Imagen</th>
        <th>Titulo</th>
        <th>Sub Titulo</th>
        <th>Url</th>
        <th > </th>
    </thead>
    <tbody>
    @foreach($noticias as $noticias)
        <tr>
            <td><img src="{!! URL::asset('/uploads/noticias/'.$noticias->image_thumb) !!}" height="50" width="auto"></td>
            <td><img src="{!! URL::asset('/uploads/noticias/'.$noticias->image) !!}" height="50" width="auto"></td>
            <td>{!! $noticias->titulo !!}</td>
            <td>{!! $noticias->sub_titulo !!}</td>
            <td>{!! $noticias->url !!}</td>
            <td>
                {!! Form::open(['route' => ['noticias.destroy', $noticias->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="/novedad/{{$noticias->url}}" target="_blank" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('noticias.edit', [$noticias->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Esta seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>